
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 14 23:54:42 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int codigoi = 8;
  public static final int codi = 23;
  public static final int codigof = 9;
  public static final int codf = 24;
  public static final int idi = 6;
  public static final int correoi = 18;
  public static final int tip = 34;
  public static final int idf = 7;
  public static final int correof = 19;
  public static final int idc = 67;
  public static final int coma = 61;
  public static final int igual = 60;
  public static final int sucursali = 44;
  public static final int sucursalf = 45;
  public static final int cantidadi = 36;
  public static final int cod = 29;
  public static final int llavei = 51;
  public static final int productot = 35;
  public static final int tamanoi = 42;
  public static final int marcai = 38;
  public static final int tipoT = 22;
  public static final int cant = 48;
  public static final int cantidadf = 37;
  public static final int inicio = 2;
  public static final int llavef = 52;
  public static final int tamanof = 43;
  public static final int marcaf = 39;
  public static final int telefonoi = 16;
  public static final int telefonof = 17;
  public static final int productof = 46;
  public static final int menos = 57;
  public static final int tel = 33;
  public static final int EOF = 0;
  public static final int mas = 56;
  public static final int error = 1;
  public static final int pcoma = 53;
  public static final int tstring = 64;
  public static final int por = 58;
  public static final int usuarioi = 4;
  public static final int usuariof = 5;
  public static final int pro = 30;
  public static final int id = 66;
  public static final int nombrei = 12;
  public static final int tiendaf = 50;
  public static final int tiend = 49;
  public static final int sucur = 47;
  public static final int nombref = 13;
  public static final int apellidoi = 14;
  public static final int apellidof = 15;
  public static final int fin = 3;
  public static final int imgi = 27;
  public static final int imgf = 28;
  public static final int cpar = 55;
  public static final int creari = 10;
  public static final int propii = 25;
  public static final int crearf = 11;
  public static final int rentero = 63;
  public static final int propif = 26;
  public static final int colori = 40;
  public static final int nom = 31;
  public static final int rdecimal = 62;
  public static final int div = 59;
  public static final int colorf = 41;
  public static final int direccioni = 20;
  public static final int dir = 32;
  public static final int direccionf = 21;
  public static final int tchar = 65;
  public static final int apar = 54;
}

